module(
    name = "theos",
    version = "0.1.0",
)

bazel_dep(name = "rules_rust", version = "0.70.0")
git_override(
    module_name = "rules_rust",
    remote = "https://github.com/bazelbuild/rules_rust.git",
    commit = "c70eb8562de80058137c8f9680b83f330f538dd4",
    patches = ["//:rules_rust_proc_macro.patch"],
)
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.17")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.95.0"],
    extra_target_triples = ["x86_64-unknown-uefi"],
)

use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")
register_toolchains("//toolchains:uefi_cc_toolchain")

cc_configure = use_extension("@rules_cc//cc:extensions.bzl", "cc_configure_extension")
use_repo(cc_configure, "local_config_cc", "local_config_cc_toolchains")
register_toolchains("@local_config_cc_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//third-party:Cargo.lock",
    manifests = ["//third-party:Cargo.toml"],
    supported_platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "wasm32-unknown-unknown",
        "wasm32-wasip2",
        "x86_64-pc-windows-msvc",
        "x86_64-unknown-linux-gnu",
        "x86_64-unknown-uefi",
    ],
)
use_repo(crate, "crates")
