package(default_visibility = ["//visibility:public"])

load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "mkrootfs",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    crate_name = "mkrootfs",
    edition = "2024",
    deps = ["//lib/crabfs:crabfs_std"],
)
