genrule(
    name = "native_init",
    srcs = [
        "child.c",
        "init.c",
        "init_reloc.c",
        "ntdll.def",
        "ntdll_reloc.c",
        "syscall_stubs.S",
        "ntdll_stubs.S",
    ],
    outs = {
        "child": ["child.exe"],
        "init": ["init.exe"],
        "ntdll_dll": ["ntdll.dll"],
        "ntdll_lib": ["ntdll.lib"],
    },
    default_outs = ["init.exe"],
    executable_outs = ["init"],
    visibility = ["PUBLIC"],
    cmd = """
set -euo pipefail

clang --target=x86_64-pc-windows-msvc -ffreestanding -fno-stack-protector -fno-builtin \
    -c "$SRCDIR/init.c" -o "$TMP/init.obj"
clang --target=x86_64-pc-windows-msvc -ffreestanding -fno-stack-protector -fno-builtin \
    -c "$SRCDIR/child.c" -o "$TMP/child.obj"
clang --target=x86_64-pc-windows-msvc -c "$SRCDIR/syscall_stubs.S" -o "$TMP/syscall_stubs.obj"
clang --target=x86_64-pc-windows-msvc -ffreestanding -fno-stack-protector -fno-builtin \
    -c "$SRCDIR/init_reloc.c" -o "$TMP/init_reloc.obj"
clang --target=x86_64-pc-windows-msvc -c "$SRCDIR/ntdll_stubs.S" -o "$TMP/ntdll_stubs.obj"
clang --target=x86_64-pc-windows-msvc -ffreestanding -fno-stack-protector -fno-builtin \
    -c "$SRCDIR/ntdll_reloc.c" -o "$TMP/ntdll_reloc.obj"
lld-link /dll /noentry /nodefaultlib /machine:x64 \
    /base:0x140000000 /def:"$SRCDIR/ntdll.def" /out:"$OUT/ntdll.dll" /implib:"$OUT/ntdll.lib" \
    "$TMP/ntdll_stubs.obj" "$TMP/ntdll_reloc.obj"
lld-link /entry:start /subsystem:native /nodefaultlib /machine:x64 /fixed:no \
    /out:"$OUT/init.exe" "$TMP/init.obj" "$TMP/init_reloc.obj" "$OUT/ntdll.lib"
lld-link /entry:start /subsystem:native /nodefaultlib /machine:x64 /fixed:no \
    /out:"$OUT/child.exe" "$TMP/child.obj" "$TMP/init_reloc.obj" "$OUT/ntdll.lib"
""",
)
