name: CI

on:
  push:
    branches: [canon]
  pull_request:
    branches: [canon]
  merge_group:
    branches: [canon]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Watchman
        run: |
          sudo apt update -y
          sudo apt install -y watchman
      - name: Install Buck2
        uses: dtolnay/install-buck2@latest
      - name: Install Nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy, rust-src
          targets: x86_64-unknown-uefi
      - name: Build Buck2 Targets
        run: |
          buck2 build //...
