name: CI

on:
  push:
    branches: [canon]
  pull_request:
    branches: [canon]
  merge_group:
    branches: [canon]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy, rust-src
          targets: x86_64-unknown-uefi, x86_64-pc-windows-msvc
      - name: Build All Targets
        run: |
          cargo xtask build
