rust_library(
    name = "udf",
    srcs = glob(["**/*.rs"]),
    crate_root = "lib.rs",
    crate = "udf",
    edition = "2024",
    visibility = ["PUBLIC"],
    deps = [
        "third-party//:byteorder",
        "third-party//:thiserror",
    ],
)
